### PR TITLE
add utilities to auto-translate languages

### PR DESCRIPTION
**Pull request by mithrand0**
In some cases, no translation is worse than having *a* translation.

This adds a script to implement auto-translation of Valve KeyValues files.

Such script can be useful, to provide some sort of usable translation for languages that are not maintained, or languages that run behind, giving translators some additional time.

The script has a config to only translate specific languages (right now french, to test). It also marks auto-translated phrases with a `*`, so people can see it is an automatic translation. It leaves already translated phrases intact.

### CODE REVIEW

**Comment by DukeDukeEm** [comment]
This probably also needs to be respected in the progress.md generation. @BenLubar

**Comment by BenLubar** [comment]
If the tool leaves the lines indented, it should work with progress.md as-is.

**Comment by mithrand0** [comment]
image

Indentation of the current files is sometimes inconsistent. I can indent, or not indent, but keeping lines intact is hard.

**Comment by ywgATustcbbs** [comment]
if possible, could you provide machine translated texts for all newly add strings using ChatGPT? openai has banned all chinese accounts they found.

**Comment by Blueberryy** [comment]
> if possible, could you provide machine translated texts for all newly add strings using ChatGPT? openai has banned all chinese accounts they found.

I think DeepL could handle it better

**Comment by ywgATustcbbs** [comment]
> > if possible, could you provide machine translated texts for all newly add strings using ChatGPT? openai has banned all chinese accounts they found.
> 
> I think DeepL could handle it better But yeah i think AI translation would help some languages

i mean machine translation + proof reading and correction. this would save a lot of time.

**Comment by BenLubar** [comment]
I'd be hesitant to use ChatGPT for anything other than a toy - it's not designed to produce correct translations, only to generate text that looks like a conversation.

**Comment by ywgATustcbbs** [comment]
I tried it before my ip was banned. Found it to be more accurate than google translation in most cases, at least on English-cChinese. Anyway, auto machine translation utility means an easier start than the current copy - paste - copy back - proof reading workflow, regardless of google translation Or chatgpt Or whatever else.

**Comment by mithrand0** [comment]
Possibly related to #791

**Comment by BenLubar** [comment]
Closing this until we go back to work on it some more so that GitHub stops saying "1 pull request"

**Pull request closed without merging**
