### PR TITLE
(multiple) Change Joystick to Gamepad and some russian translation update

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Review by DukeDukeEm — COMMENTED** [review]
Isn't the joystick still on the gamepad. And isn't it still used to change your view? Or are you looking around through moving your gamepad itself (gyro)?

**Comment by Blueberryy** [comment]
Isn't it's that thing?
joystick

**Comment by DukeDukeEm** [comment]
We seem to be both a bit wrong 😄 Wikipedia says it's an [Analog Stick](https://en.wikipedia.org/wiki/Analog_stick), a variant of a joystick.

**Comment by BenLubar** [comment]
Joysticks were basically fancy arrow keys for some of the first gaming PCs

**Comment by DukeDukeEm** [comment]
XD

image

**Pull request merged**
