### PR TITLE
(swedish)Update reactivedrop_swedish.txt

### PR DESCRIPTION
**Pull request by Crazymanbos**

### CODE REVIEW

**Comment by Crazymanbos** [comment]
I literally give up trying to translate the idiotic achievments. I dont know how to use some automatic translation tools or whatever you guys are telling me, why cant I just translate them myself!?!?!?!?!?!?!

**Comment by Crazymanbos** [comment]
And where do I find that to run????? Why do we have to use stupid robots to do stuff for us when I can translate it without the stupid "translation-sync-tool.exe" that I dont even know where you find it

**Comment by Blueberryy** [comment]
Just use Github Desktop and clone your fork to your machine and then you will find it. Trust. It will make things more easier

**Comment by DucDuyGaming** [comment]
> the stupid "translation-sync-tool.exe" that I dont even know where you find it

the exe can be found in the "utils" folder of the repository, but to execute it, i believe you need to download this repository into your desktop. however if you dont want to run the exe, or dont want to download a copy of this repository into your computer, just cover the achievements string in reactivedrop_swedish.txt and 563560_loc_swedish.vdf by yourself. the search bar is your best friend, and cover every strings that have the exact same words if youre unsure

as for GitHub Desktop that berry mentioned, i believe it is this: https://desktop.github.com/

**Comment by DucDuyGaming** [comment]
if you downloaded GitHub Desktop, i will try my best to help you. do as follow:

- link your GitHub account, and let it automatically fill in your name and address
- click on "Clone a repository from the Internet...", then choose your folk of this repository. pick your prefered empty folder that you want to extract the content into, such as a newly created folder on your desktop
- click clone, and then wait for it to finished
- after youre done, translate the achievement strings in reactivedrop_swedish.txt on the branch that you will make a PR on, within the folder itself
image
image
the GitHub Desktop should detect your change and automatically update GitHub Desktop
- once you feel like youre done, go to the "utils" folder on your desktop, and execute "translation-sync-tool.exe". this will sync your achievement translations to 563560_loc_swedish.vdf

**IMPORTANT:**
   - if you translate the achievement strings in 563560_loc_swedish.vdf instead of reactivedrop_swedish.txt and then run the tool, all your commits in 563560_loc_swedish.vdf will vanish without syncing into reactivedrop_swedish.txt
  -  since this exe is not very commonly executed, it will most likely be blocked by your anti-virus. exclude the folder/file from being checked within your anti virus
  
if you do it right, it should look like this
image
- write down your summary and description of the commit
image
choose your branch that you want to merge your commit into
image
then press "commit to [branch]"
- make a PR on github.com using that branch

- good luck and have fun

**Pull request closed without merging**
