### PR TITLE
(multiple) clarified auto-deletion feature

### PR DESCRIPTION
**Pull request by DukeDukeEm**
\+ (multiple) better known phrase for achievement
\+ (german) translated mortarbug story
\+ (german) hotfix patch notes

### CODE REVIEW

**Comment by BenLubar** [comment]
The achievement name is a reference to https://www.imdb.com/title/tt0114214/. Is there a reason you're changing it?

**Comment by DukeDukeEm** [comment]
I just realized while translating it the phrase "quick and easy" is a known phrase. The other one isn't. But now that you're telling me it is a reference to a movie. How about naming it after the reference? Like "The Quick and the Dead", it would fit to a marine killing a boomer. And it would be a real reference fitting to your link.

**Comment by DukeDukeEm** [comment]
I changed it, it's great actually, because now I can use the germans movie title as a translation too.

**Comment by DukeDukeEm** [comment]
The only thing to the term ["quick and dead"](https://en.wikipedia.org/wiki/The_quick_and_the_dead_(idiom)) i could find is from a translated bible, 1830.

**Comment by BenLubar** [comment]
`rd_demo_auto_warning_unlimited` is used when the recording limit is negative, which means that new recordings are automatically created, but *no* recordings are deleted.

`rd_demo_auto_warning_generic` is used for positive limits, and `rd_demo_auto_warning_deletion` is used on recordings with names matching the auto-deletion code's search parameters when a positive recording limit is active.

**Comment by BenLubar** [comment]
> The only thing to the term ["quick and dead"](https://en.wikipedia.org/wiki/The_quick_and_the_dead_(idiom)) i could find is from an translated bible, 1830. Edit: ... and ~3 youtube videos which seem to have forgotten the meant movies name ... Edit: given, your yt results may differ

Upon closer inspection, the movie title appears to be a reference to that bible verse, so they're the same meaning - someone is quick (the marine) and someone else is dead (the boomer).

**Comment by DukeDukeEm** [comment]
If we have problems finding the reference, who should be the person to get it? Do we really want to reference a thing nobody knows anymore? I mean a western from ~30 years ago, yea sure, why not. But a religious book from close to 200 years ago?

**Comment by DukeDukeEm** [comment]
> `rd_demo_auto_warning_unlimited` is used when the recording limit is negative, which means that new recordings are automatically created, but _no_ recordings are deleted.
> 
> `rd_demo_auto_warning_generic` is used for positive limits, and `rd_demo_auto_warning_deletion` is used on recordings with names matching the auto-deletion code's search parameters when a positive recording limit is active.

I realized that the description for how the auto-deletion works, only shown while selecting the only option which does not lead to any auto-deletion anyhow. I saw these strings in the recordings-window which can be accessed from the main-menu. Are there any other places in which they show up?

**Comment by BenLubar** [comment]
Nope, they only show up on that screen.

**Pull request merged**
