### PR TITLE
translate eula to some languages

### PR DESCRIPTION
**Pull request by mithrand0**
Translation or EULA to languages:

- [x] Dutch
- [x] Finnish
- [x] French

### CODE REVIEW

**Comment by Blueberryy** [comment]
I will include EULA at my pull request before new update release

**Comment by BenLubar** [comment]
Is this ready to merge?

**Comment by BenLubar** [comment]
Finnish is missing links.

**Comment by mithrand0** [comment]
Credits for Finnish translation go to 'ghlaaku', credits for French go to 'trick-master'.

**Comment by BenLubar** [comment]
What's ghlaaku's Steam profile?  I believe trick-master already has the translator medal.

**Pull request merged**
