### PR TITLE
closedcaption_, reactivatedrop_ translation.. wait?

### PR DESCRIPTION
**Pull request by BRAIN-IS-BACK**
**some part is.. error.."

I made a mistake a while ago.
But I did it **right this time.**

**https://github.com/ReactiveDrop/reactivedrop_translations/issues/68**

As I said in the previous issue, I unified all translations related to Korean.
Before I joined the translation, there were other translators. And the above situation occurred because the translation between them and me was different.

There are two modified files, and these two are not completely 100%. Additional translation is needed later. However, **the problem of translation unification has been solved.**

Additionally, I translated Alien as "외계놈들,외계놈".
Some lines say Alien instead of Swarm.

The word **"외계놈들"** is a tougher word than Alien(외계) itself.
Soldiers will not be calling **Mr. alien brother** by courtesy of disgusting, repulsive alien creatures.

### CODE REVIEW

**Comment by BRAIN-IS-BACK** [comment]
1 failing check??
got. another failed.. brh..

**Comment by BenLubar** [comment]
Looks like the `achievements/563560_loc_koreana.vdf` file needs to be updated (I can do that if you don't know how)

and vegas.Reloading1 and vegas.Reloading2 are swapped in the closed caption file

**Comment by BRAIN-IS-BACK** [comment]
> Looks like the `achievements/563560_loc_koreana.vdf` file needs to be updated (I can do that if you don't know how)
> 
> and vegas.Reloading1 and vegas.Reloading2 are swapped in the closed caption file

oh, maybe i can edit 563560_loc_koreana.vdf.
and i will check vegas.Reloading1 and vegas.Reloading2 on closed caption file

**Comment by BRAIN-IS-BACK** [comment]
> Looks like the `achievements/563560_loc_koreana.vdf` file needs to be updated (I can do that if you don't know how)
> 
> and vegas.Reloading1 and vegas.Reloading2 are swapped in the closed caption file

and... do you know why he hell 1 failing check on [reactivedrop_koreana.txt]?

**Comment by BRAIN-IS-BACK** [comment]
@BenLubar
First, close the REQUEST.
I will revise it again and do REQUEST again.

**Comment by DukeDukeEm** [comment]
> and... do you know why he hell 1 failing check on [reactivedrop_koreana.txt]?

@BRAIN-IS-BACK your CI-Checks fails, I documented how to fix this here
https://github.com/ReactiveDrop/reactivedrop_translations/wiki/How-to-translate-using-vscode#continous-integration

**Comment by DukeDukeEm** [comment]
@BRAIN-IS-BACK and you do not have to close your pull request when the checks fail, you just fix your problem and commit again, everything you do since you opened the PR will just be added to the same open pull request, so you can fix and add stuff until Ben has time to merge it.

**Comment by DukeDukeEm** [comment]
@BRAIN-IS-BACK you ARE using Github (the plattform holding the code), and you are using git. It is a code versioning system, not directly related to Github. It was invented by Linus Torvalds, which also develops the Linux Kernel. What you AREN'T using is (I'm guessing here) vscode, which is not important. I am myself not a guru with these things, I just wrote the translation article with vscode in mind because it's the only thing I am used to. But the wiki holds information apart from vscode too, so you can get something out of it even if you do not use it as described in the wiki.

**Pull request closed without merging**
