### PR TITLE
(swedish) reduction achievements

### PR DESCRIPTION
**Pull request by DucDuyGaming**
given permission by [Crazymanbos](https://github.com/Crazymanbos) to try and put some of the remaining of what he tried to contribute into the main repository

### CODE REVIEW

**Comment by DucDuyGaming** [comment]
This shouldn't happen. the "translation" I commented out are still in English. And in the main reactivedrop_swedish.txt it still have the indention. Something is broken, or I missed something

As for the Reduction achievements, it did not send out an error

**Comment by Crazymanbos** [comment]
Yeah, sometimes it works, sometimes it dosent. Its just weird.

**Comment by jhh8** [comment]
the issue is probably missing quotation marks in commented out lines

**Comment by DucDuyGaming** [comment]
I checked back and forth, nothing out of ordinary. I saw that when Ben [sync the achievement page](https://github.com/ReactiveDrop/reactivedrop_translations/pull/1193/commits/0cf500ed6e1ee91af69d72cbcb8356a6216ec21e), the sync also removed the part that commented out the English strings and served it as if it is a "Swedish translation"

**Comment by jhh8** [comment]
ok. i think the issue is that you cant translate only name and leave description untranslated for an achievement

**Comment by Crazymanbos** [comment]
Eh, forget about this one. I will probably come back for these later on when going through as much as possible and see if it keeps failing. You can close this pull request.

**Comment by Duke-M-commits** [comment]
I think the issue is: the achievements should be translated in reactivedrop_swedish.txt
After saving you should execute utils/translation-sync-tool.exe (this will write the achivements-vdf-file for you).

**Comment by DucDuyGaming** [comment]
Could be true. And if what jhh8 said is true, the error was caused for translating the titles but not it descriptions in reactivedrop_swedish. The only way to verify to see if it is true is to translate it, but I can't do it. As for now, I will revert my correction, and then just gonna try and make the Reduction achievement strings go through

**Comment by BenLubar** [comment]
If you click the Checks tab at the top of this page, it will show the differences between what you wrote (red) and what the translation sync tool changed it to (green).

**Pull request merged**
