### PR TITLE
Update reactivedrop_swedish.txt

### PR DESCRIPTION
**Pull request by Crazymanbos**
Reduction campaign translated.

### CODE REVIEW

**Comment by DucDuyGaming** [comment]
sad to see all your hard work go to vain. i could help you with this if you want, but i cannot do it on my own folk because i am also working for the translations, so you need to give me write access on your folk if you can

**Comment by Crazymanbos** [comment]
> sad to see all your hard work go to vain. i could help you with this if you want, but i cannot do it on my own folk because i am also working for the translations, so you need to give me write access on your folk if you can

Eh, its fine. Im just trying my way to see how its supposed to be done. Because the guide dosent help too much really, but im trying. You only learn by trying.

**Comment by BenLubar** [comment]
You need to make the changes to each file on the same branch of your repository.

**Comment by Crazymanbos** [comment]
> You need to make the changes to each file on the same branch of your repository.

First thing, sorry for wasting all of your time seing my failures. And I will try that then.

**Comment by DucDuyGaming** [comment]
first off, translate on one file, in this case, the achievement (for web) file, on the main branch. don't create a separate branch. it is not the requirement, but it is so to be more "controlled"

**Comment by DucDuyGaming** [comment]
after finishing, while in that branch, go and create a PL from the "Pull requests" tab in the folk itself. it will automatically fill in the branch. afterward, if there is any error, either I or Ben can tell you what to do

**Comment by Crazymanbos** [comment]
I sent in a new one but it failed. Go look in closed pull requests for that one

**Comment by DucDuyGaming** [comment]
dont know why that happened

also, Ben syncing the achievement files resulted in some of the description staying in english, not commented out

**Comment by DucDuyGaming** [comment]
turn out i can just also create a different branch to create a separate contribution. i put in some of your work you tried to put it into the main repository, and then i will make a PL and see if it work or not, or have to fix something. but first i need to ask if you want me to do it

**Comment by Crazymanbos** [comment]
yeah go ahead and try that

**Pull request closed without merging**
