### PR TITLE
Update reactivedrop_portuguese

### PR DESCRIPTION
**Pull request by TheScientistPT**

### CODE REVIEW

**Comment by BenLubar** [comment]
Do you have git installed locally, or are you doing this through the web UI?

If it's installed locally, run the EXE file in the utils folder to sync the achievement file.

**Comment by TheScientistPT** [comment]
I have git installed locally, yes. Tried running the EXE file in the utils folder, does it change anything in my local git repo?

**Comment by BenLubar** [comment]
It should have changed `achievements/563560_loc_portuguese.vdf`

**Comment by TheScientistPT** [comment]
I don't see any changes to that file.

**Comment by BenLubar** [comment]
I'll get the changes added back into both files.

**Pull request merged**
