### PR TITLE
(italian) Translated all "marines" to "soldati" for consistency

### PR DESCRIPTION
**Pull request by LeecanIt**

### CODE REVIEW

**Comment by Steffo99** [comment]
Marine sounds better than Soldati in my opinion, maybe we should use that everywhere?

**Comment by Steffo99** [comment]
Btw, do we have a [lexicon](https://github.com/ReactiveDrop/reactivedrop_translations/wiki/Lexicon) somewhere?

Games feel a lot better if all strings are consistently translated!

**Comment by DukeDukeEm** [comment]
You can just copy over the lexicon I wrote into the wiki of the LeecanIt fork.
@LeecanIt you just have to enable the wiki in the repo settings so Steffo99 can use it.

**Comment by BenLubar** [comment]
I've added an extra heading level to https://github.com/ReactiveDrop/reactivedrop_translations/wiki/Lexicon so you don't have to do it in a different wiki

**Pull request merged**
