### PR TITLE
(swedish) Achievment test

### PR DESCRIPTION
**Pull request by Crazymanbos**

### CODE REVIEW

**Comment by BenLubar** [comment]
Needs to also be changed in the achievements folder. I should really get rid of those and just create them locally.

**Comment by Crazymanbos** [comment]
Yes I noticed that, I changed both files, dunno why it only commited the first one

**Comment by BenLubar** [comment]
oh, another quirk: if either the name or description of an achievement differs from english, it considers both to have been translated for the achievement file

**Comment by Crazymanbos** [comment]
bro what

**Comment by DucDuyGaming** [comment]
> bro what
he mean that, if either the name or the description of an achievement in reactivedrop_swedish.txt is in non-english, it is considered "translated" for both string (the name and it description) in the 563560_loc_swedish.vdf file (the sync tool will insert full english words for the string that you did not translated, but you did for the other string)

image


ps: you seem to _really_ have trouble translating the achievement strings, and usually just close down PR as soon as you're confused. if you want to, i can try to help you (just talk through Steam), although i won't restore your previous translations that you attempted to push through

**Pull request closed without merging**
