### PR TITLE
(schinese) I'm taking a guess here

### PR DESCRIPTION
**Pull request by DukeDukeEm**
there was a character too much?

### CODE REVIEW

**Review by zhongqingsong — COMMENTED** [review]
@DukeDukeEm Uh, I don't see what you mean.You mean, I deleted a character, that's a problem, or confused? Let me explain, we focus on the last few characters. “英雄们” and “英雄”.
"英雄们" is based on the English translation and retains the plural. 
However, for the following considerations, I have deleted the "们" at the end.
1. This is a title translation, so it should be easy to understand. Adding a "们" is actually not suitable for Chinese semantics. As we all know, Chinese does not distinguish between singular and plural from words. So, when I went back and analyzed the translation, out of common practice, I removed the last character.
2. Removing this "们" will not affect any meaning expression, and at the same time make the expression of the title more concise.

**Comment by DukeDukeEm** [comment]
> @DukeDukeEm Uh, I don't see what you mean.You mean, I deleted a character, that's a problem, or confused? Let me explain, we focus on the last few characters. “英雄们” and “英雄”. "英雄们" is based on the English translation and retains the plural. However, for the following considerations, I have deleted the "们" at the end.
> 
>     1. This is a title translation, so it should be easy to understand. Adding a "们" is actually not suitable for Chinese semantics. As we all know, Chinese does not distinguish between singular and plural from words. So, when I went back and analyzed the translation, out of common practice, I removed the last character.
> 
>     2. Removing this "们" will not affect any meaning expression, and at the same time make the expression of the title more concise.

Thank you for the explanation.
I was just checking if the HoIAF is written the same way (for recognition value) in all places.

**Comment by zhongqingsong** [comment]
> 

Mmmmm, yes. This translated text is the same as in the schema. They are all "星际武装部队的英雄".

**Comment by DukeDukeEm** [comment]
Both of these repos show "星际武装部队的英雄们".
Official repo: https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/resource/reactivedrop_schinese.txt#L5814
Your repo: https://github.com/zhongqingsong/reactivedrop_translations/blob/master/resource/reactivedrop_schinese.txt#L5814

**Comment by zhongqingsong** [comment]
> Both of these repos show "星际武装部队的英雄们". Official repo: https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/resource/reactivedrop_schinese.txt#L5814 Your repo: https://github.com/zhongqingsong/reactivedrop_translations/blob/master/resource/reactivedrop_schinese.txt#L5814
> 
> My changeset deleted this char: https://github.com/ReactiveDrop/reactivedrop_translations/pull/331/files

Sorry, I thought you had modified the current document, so I didn't change it. 
So now do you merge this PR directly, or do I need to submit a new PR?

**Comment by DukeDukeEm** [comment]
@zhongqingsong I changed it, Ben reviewed it and decided you should review it, your review was positive, so now Ben merged it into the official repo, and we both will sync it from there back in our repos. I did my changeset in my repo, but on a special branch, so it would not have been in my commit history if the change would have been denied.

**Pull request merged**
