### PR TITLE
(vietnamese) major translating 

### PR DESCRIPTION
**Pull request by DucDuyGaming**
Apologize if this is too much, this took way longer than I imagine. The main thing about this PR is that it fully complete the entire achievement file for the Steam store page, and a mouthful of the strings in the main reactivedrop_vietnamese.txt file that is related to it, + the achievement strings for the in-game achievement tab and a few misc changes. Again, let me know if there is any problem, but keep in mind that I'm terrible at coding, and are still a novice on GitHub, so I might have some issues when solving problems

Also, should also mention this too so I don't have to create an issue, I saw that, despite already translated it, the workshop description remain untranslated when I switch to Vietnamese language. The workshop tags translation are already applied. Maybe have a look about it

### CODE REVIEW

**Review by BenLubar — CHANGES_REQUESTED** [review]
https://github.com/ReactiveDrop/reactivedrop_translations/pull/1090/checks

The bot found a few things you need to change, and then it should be ready to go in the game:

- A few lines have indentation that's confusing it - fully translated lines should have no indentation (for both the translated line and the `[english]` line, as well as any notes that come before both) and lines that need to be looked at should have 2 tabs at the start.
- There are a few places where you translated the `[english]` line instead of the translated line - should be as simple as swapping them to fix.
- The rest of the changes the bot wants are just consistency for strings that need to be the same in multiple files.

**Comment by BenLubar** [comment]
> Also, should also mention this too so I don't have to create an issue, I saw that, despite already translated it, the workshop description remain untranslated when I switch to Vietnamese language. The workshop tags translation are already applied. Maybe have a look about it

Good catch - should be fixed as soon as the cache expires.

**Comment by DucDuyGaming** [comment]
All fixed. Well, aside from this as shown below, I look back and forth for error, and I still have no clue why this cause a fail check. Probably not a problem, I guess
image

**Comment by BenLubar** [comment]
I'll check what's going on locally after I merge.

**Comment by Crazymanbos** [comment]
Holy moly

**Pull request merged**
