### PR TITLE
(english) medals renamed to collectibles

### PR DESCRIPTION
**Pull request by DukeDukeEm**
\+ (english) replaced unused string, just for consistency

### CODE REVIEW

**Comment by DukeDukeEm** [comment]
I'm wondering: how do I mark to-be-retranslated strings in json-files? (they include indentations already)

**Comment by BenLubar** [comment]
If a string in the item schema is changed to the point where it needs a complete retranslation I'd just delete the translated string.

**Comment by BenLubar** [comment]
The ones with `"name_color": "70B04A"` should probably remain "Community Medal"

**Comment by DukeDukeEm** [comment]
> The ones with `"name_color": "70B04A"` should probably remain "Community Medal"

Getting the rarity in there was my initial argument. Why should they remain like this?

**Comment by BenLubar** [comment]
I think some Valve games call it "quality" versus "rarity"

https://developer.reactivedrop.com/item-guidelines.html

Basically there's the scale of items in ascending rarity near the end of the first table and then the stuff above and below that is the quality, so only "normal" quality shows the rarity.

That's how it works in TF2 and Dota 2, at least.

**Comment by DukeDukeEm** [comment]
I don't think so, but maybe you can give me some examples.
This is what I found:
### CS:GO
Here's a [Contraband Sticker](https://steamcommunity.com/market/listings/730/Sticker%20%7C%20Howling%20Dawn) with the same naming scheme, Contrabands can't drop.

### TF2
[This page](https://wiki.teamfortress.com/wiki/Valve_(quality)) shows an item which had it's quality even integrated into it's name.
And [here's another one](https://wiki.teamfortress.com/wiki/Community_(quality)), it's the 'Community Wrench'
So after this scheme, the medal "Reporter" should be named "Community Reporter".

In the place other games have their quality displayed, TF2 shows "Level 50 Wrench". 
I actually never understood what these Levels mean.

### Dota2
Dota puts the quality 'Self-Made' into the name and rarity into the display_name, so they use both, quality and rarity, and they are both placed very obviously:
image

**Comment by DukeDukeEm** [comment]
What of these are you planning (or explicitly not) to integrate?
* craftables
* drops
* community items given by the game devs

Depending on what will be implemented in which combination these naming conventions could change and get pretty chaotic.

**Comment by BenLubar** [comment]
We are planning both item drops and crafting:

https://github.com/ReactiveDrop/reactivedrop_public_src/issues/508

The currently-existing weapons will still be unlocked by leveling up (the inventory versions are "Strange" like in TF2). The new weapons for the 7th anniversary will have other unlock mechanisms (multiple ways to unlock each).

I think the display_type should be name color based, so all of the light green ones are Community, etc.

We're not putting the type in the name like in TF2 because "Community Reporter" sounds weird as an item name.

**Comment by DukeDukeEm** [comment]
> We are planning both item drops and crafting:
> 
> [ReactiveDrop/reactivedrop_public_src#508](https://github.com/ReactiveDrop/reactivedrop_public_src/issues/508)

Oh boy, I should really start to read the src-repo.

> The currently-existing weapons will still be unlocked by leveling up (the inventory versions are "Strange" like in TF2). The new weapons for the 7th anniversary will have other unlock mechanisms (multiple ways to unlock each).
 
Ok, thanks.

> I think the display_type should be name color based, so all of the light green ones are Community, etc.

 I think so too, a color-code should have an relating name-code and that's a good place for it.

> We're not putting the type in the name like in TF2 because "Community Reporter" sounds weird as an item name.

I too wouldn't like that, after my scheme it would be "Legendary Reporter".
I just wanted to point out that it's not a one vs the other scheme in all cases. They sometimes get and sometimes don't get combined, in different places.

I'll close this one and think about a new one.

**Pull request closed without merging**
