### PR TITLE
(multiple) formattings and fixes

### PR DESCRIPTION
**Pull request by DukeDukeEm**
Ok, that's a big one. I normalized the way the To/From fields are written like they are sent through the same mail-system while conserving the individual mail-contents writing styles.

Formatted mails consistently:
* PDA owner names use abbreviated titles and feature full names if possible (some aren't known, some would loose their only mention of a title at all, these have been left untouched)
* Comments are written in english
* Owner comments read names by their in-story used name like 'Lt. Cain' (fitting to PDA owner names), in difference, mail to- or from-fields spell out their first and last name like 'John Cain' (except spam-mails, they should look more spammy and include more important sounding names)
* All mails feature now owner (if possible) and inbox/sent sections through comments
* Consistent line breaks

Other stuff:
* The word 'Say :' in ingame-chat has been shortened to 'Say' as the ingame-ui provides a separator at the end of the word anyway (and a blinking cursor too)
* ~~Changed 'Ten. Cain' to 'Lt. Cain' in the brazilian translation according to wikipedia~~
* Changed 'Lt. Cain' to 'Ten. Cain' in the italian translation according to wikipedia
* Sarah Weiss was a Captain in some cases, has been corrected to her the more often used title Sergeant
* The titles of Jacques und Helen Moreau changed from 'professors' to 'doctors' in one mail
* Replaced a rl-reference with an in-universe one
* Removed lots of dots at the end of mail signatures

### CODE REVIEW

**Comment by DukeDukeEm** [comment]
@MakinDay please review 18df419a5c74335c5de944e1e9ac9cb2920d3b83
@Blueberryy please review 6cf174090073bdbff93c723a32ab5eb4f01ce337
@zhongqingsong please review 14624bcec14534f72d59d499a5465ac9047008ab
@Deerlord0 please review c2aae6683158fd34aa0b61f2b961c195a227c71e
@FurtadoPires please review b86758131c321d3afdd8ec5048e51f39153647d9
@BRAIN-IS-BACK please review 25438c1b72c73f1d515ebfe46acec7d8ffc04c66
@wawawawawawawa please review 979f0f8e5b876d423eb2e57967dfa031f4c8b6c6

**Comment by Blueberryy** [comment]
why Sarge isn't Sergeant?

**Comment by DukeDukeEm** [comment]
> why Sarge isn't Sergeant?

In this case it's the marines name itself.

**Comment by FurtadoPires** [comment]
@DukeDukeEm 

> Comments are written in english

-No objection in this one

> Changed 'Ten. Cain' to 'Lt. Cain' in the brazilian translation according to wikipedia

-I made this adaptation due to the fact that we don't have the "Lieutenant" patent in brazilian army, hence why I had to adapt to 'Tenente' (Ten.)

-About `Dra. Julie Duval` "doctor" is a word with gender in portuguese, so just using "dr" abbreviation can mean "male-doctor Julie Duval". Making a parallel in english would mean like call "Mr Julie" instead of "Ms Julie". The same can be considered to any other female doctor.

I would also suggest the translators to always remember to adapt the date format of emails to the ones your country uses, like in my case I always change the "MM/DD/YYYY" to "DD/MM/YYYY" in order to not confuse players who might be interested in the game's "lore".

**Comment by DukeDukeEm** [comment]
@FurtadoPires thanks.
- Ten. : I looked up the portugese wiki, which is probably not right after your explanation, I'll change that back.
- Dra. : Ok, I'll change that back too.
- Dates: Ugh ... I had a try on that. Didn't work out well. The problem is: I can't convert to my german or the ISO date because they would force me to set a definitive year (this might apply to other languages too). And as far as I got ... not everybody is happy to canonize the story into a fixed year. So I refrained from that and left the dates untouched.

**Comment by FurtadoPires** [comment]
> Ten. : I looked up the portugese wiki, which is probably not right after your explanation, I'll change that back.

-Consider [this one](https://pt.wikipedia.org/wiki/Hierarquia_militar_do_Brasil) when revising the `brazilian` version, can't say about the `portuguese` one since I'm not maintaining that one, se you have to check with then

> Dates: Ugh ... I had a try on that. Didn't work out well. The problem is: I can't convert to my german or the ISO date because they would force me to set a definitive year (this might apply to other languages too). And as far as I got ... not everybody is happy to canonize the story into a fixed year. So I refrained from that and left the dates untouched.

-Another thing I would suggest is to standardize the date format used in emails, like some of them uses "YYYY" while others uses "YY". I think respecting one of those formats could make it possible to automate the conversion somehow.

**Comment by MakinDay** [comment]
It's all good in Italian, nothing to report

**Comment by BRAIN-IS-BACK** [comment]
ok... i saw everything in https://github.com/ReactiveDrop/reactivedrop_translations/commit/25438c1b72c73f1d515ebfe46acec7d8ffc04c66

There seems to be no particular problem.
You can apply it as it has been changed.

**Comment by Deerlord0** [comment]
almost ok about Japanese. Just need some changes.


"asw_pda_owner_name_lieutenant_gael_florenza" in reactivedrop_japanese.txt
change ゲール・フローレンス大尉 to ゲイル・フローレンス大尉 for consistency.

"asw_pda_owner_name_doctor_joseph_palmer" and "asw_pda_owner_name_doctor_joseph_palmer" in reactivedrop_japanese.txt
エミリー・ホガース博士 and ジョセフ・パーマー博士 are already written in full name so no need to change.

"MailBody1D" in mail/tilarus01port_PublicMessage2_japanese.txt
ゲオテラ本社 should be ジオテラ本社 if this 'Geo' have same mean as earth.


I will change them later by myself if you just commit this big formatting fixes.

**Comment by DukeDukeEm** [comment]
@Deerlord0 I‘ll fix this, thanks.

**Comment by Blueberryy** [comment]
> 

just get back translated sarge (Сержант)

**Comment by Blueberryy** [comment]
> > 
> 
> just get back translated sarge (Сержант)

And Joseph Conrad is Джозеф Конрад

**Comment by DukeDukeEm** [comment]
I added a second batch of changes. 
More owner infos. And lots of dots in end of mail-signatures have been removed.
PS: the linked merge in the commit message is a mistake, just ignore it.

**Comment by DukeDukeEm** [comment]
> -Another thing I would suggest is to standardize the date format used in emails, like some of them uses "YYYY" while others uses "YY". I think respecting one of those formats could make it possible to automate the conversion somehow.

I would suggest to switch all translation to one date format. The [ISO](https://en.wikipedia.org/wiki/ISO_8601) date.
* it fits in the futuristic setting
* it's easily distinguishable by using an seperator not used in any other widely used format
* it reads left to right in [most-to-least-significant](https://en.wikipedia.org/wiki/Significant_figures) order
* YY works until the next century comes, YYYY works until the next decamillennium comes

**Comment by DukeDukeEm** [comment]
@zhongqingsong please replace 'professors' with 'doctors' in [this file](https://github.com/DukeDukeEm/rd_translation_german/edit/master/resource/news/antheonmissingnews_schinese.txt)
@Deerlord0  please replace 'professors' with 'doctors' in [this file](https://github.com/DukeDukeEm/rd_translation_german/edit/master/resource/news/nh_news_prospectus_japanese.txt)

**Comment by FurtadoPires** [comment]
> I would suggest to switch all translations to one date format. The [ISO](https://fits.gsfc.nasa.gov/iso-time.html) date YYYY-MM-DD
> 
>     * it fits in the futuristic setting
> 
>     * it's easily distinguishable by using an separator not used in any other widely used format
> 
>     * it reads left to right in most-to-least-significant order
> 
>     * YY works until the next century comes, YYYY works until the next decamillennium comes

I'm up to any standard, as long as it's intuitive to the readers, but it's up to @BenLubar to decide that I think

**Comment by Blueberryy** [comment]
> I would suggest to switch all translations to one date format. The [ISO](https://fits.gsfc.nasa.gov/iso-time.html) date YYYY-MM-DD
> * it fits in the futuristic setting
> * it's easily distinguishable by using an separator not used in any other widely used format
> * it reads left to right in most-to-least-significant order
> * YY works until the next century comes, YYYY works until the next decamillennium comes
> 

Yes i think boss should decide what to do with all that dates thing

**Comment by BenLubar** [comment]
I think the two digit years and non-ISO date formatting is part of the game's retrofuture aesthetic, just like how there are CRT monitors and enormous PDAs (although that last part might be mostly due to the game's camera).

If a translator thinks ISO date formatting works better for their language, I trust their judgement, but the English translation will probably stay with the two digit years and American date formatting.

**Comment by DukeDukeEm** [comment]
The whole Jacob's Rest campaign plays in a timespan of 13 days, same month, same year.
I doubt there was put very much though into the styling of the aesthetics. I think this was just an oversight which has been autotranslated into all originally offered languages.
I made a statistic about the overall used date ranges here:
https://github.com/ReactiveDrop/reactivedrop_translations/wiki/Date-formats-&-time-ranges-used

**Comment by zhongqingsong** [comment]
oh oh sorry, I haven't noticed this issue until now. I thought you were translating the game text, so I didn't click on it. Until I noticed this hadn't been closed off for days. So I clicked on it.
I review now.

**Comment by DukeDukeEm** [comment]
@zhongqingsong 
With reporting back I just meant, write me (I do not have the rights to designate reviews to others on this repo).
1. Yes, these 2 are different: a Doctor is a title got through studies and Professor is an advanced teaching qualification as an teacher
2. You are right, I've send you the wrong link, sorry. It's about the file `news/nh_news_prospectus_schinese.txt`
3. Ok, so now I only have to wait for someone who can verify the french changes.

**Comment by DukeDukeEm** [comment]
Ok, I'm pretty confident this is ready for integration. I went through the french stuff again and realized that doesn't need a review, it's all whitespaces and formattings, no changes which really need a translators review.

**Comment by zhongqingsong** [comment]
> * [x]  @Deerlord0  please replace 'professors' with 'doctors' in [this file](https://github.com/DukeDukeEm/rd_translation_german/edit/master/resource/news/nh_news_prospectus_japanese.txt)
> * [ ]  @zhongqingsong please replace 'professors' with 'doctors' in [this file](https://github.com/DukeDukeEm/rd_translation_german/edit/master/resource/news/nh_news_prospectus_schinese.txt)
> 
> I've send you an invite to web-edit it directly in my repo.

It's OK, When I translated, I was use 'professor'. It's consistent with what you're asking for now. I can confirm it.

**Comment by BenLubar** [comment]
This is nearly a thousand files changed, and multiple people have already looked it over, so I'm just going to merge it and if something breaks we'll fix it after.

**Pull request merged**
