### PR TITLE
Fixed typo and update russian translation

### PR DESCRIPTION
**Pull request by Blueberryy**

### CODE REVIEW

**Comment by BenLubar** [comment]
I think the spelling is intentional but @jhh8 would know for sure

**Comment by Blueberryy** [comment]
> I think the spelling is intentional but @jhh8 would know for sure

well it's xenomite in swarmopedia

**Comment by jhh8** [comment]
need some backstory to the name of this alien. i honestly have no clue where xenomite or xenomyte came from, i think chinese asbi community started calling it that back in the day (shortly after launch of rd) and everyone adapted to that, including swarmopedia (xenomite is a pokemon). When writing these pda's i also thought its the official name. nowadays i would call it defanged parasite or maybe harvesite, these names appear officially in code or files. the only thing close to xenomite appearing anywhere is xenonite which appears in wikipedia

**Review by jhh8 — APPROVED** [review]

**Review by BenLubar — CHANGES_REQUESTED** [review]
If we're correcting the spelling of xenomite, we should also fix the spelling of parasite in these strings.

**Comment by DukeDukeEm** [comment]
Some code comments name them "Harvesite". How about that?

**Pull request merged**
