### PR TITLE
Update reactivedrop_swedish.txt

### PR DESCRIPTION
**Pull request by Crazymanbos**
Updated a lot of random stuff that weren't translated yet. I hope I did it right this time.

### CODE REVIEW

**Comment by DucDuyGaming** [comment]
there are currently like, 3 pull requests using 3 different branches here. try and merge all alternate branches (like patch-2 and patch-3) with commits into the main branch, then make a PL on that branch. the easiest way to make PL is to be in that branch, then make a PL from the "Pull requests" tab in the folked repository itself, as it will auto fill in the branch that you want to merge into what branch. while it is not entirely harmful, i think it might be harder for the bot to detect "unintended changes" if it is not through a single PL

**Comment by Crazymanbos** [comment]
Well i dont understand. Maybe this translating stuff isnt for me

**Comment by DucDuyGaming** [comment]
it just take a while to understand how PL and branches work. your translation is not in vain

**Comment by DucDuyGaming** [comment]
can you try and merge patch-2 and patch-3 into the main branch in the folk. just do what you did in merging patch-1

**Pull request merged**
