### PR TITLE
Mission filter, Vegas's realoding subs, workshop visitors, new swarmo…

### PR DESCRIPTION
**Pull request by Deerlord0**
Mission filter for official/addon.
Swapped "vegas.Reloading1" and "vegas.Reloading2" so now they match voice and subs.
Workshop visitors counter uses same words as steam workshop pages.

### CODE REVIEW

**Comment by DukeDukeEm** [comment]
> Mission filter for official/addon. Swapped "vegas.Reloading1" and "vegas.Reloading2" so now they match voice and subs. Workshop visitors counter uses same words as steam workshop pages.

Does this mean we all should swap these 2?

**Comment by Deerlord0** [comment]
> 
I think so. At least, they are not matched in English too.

**Comment by DukeDukeEm** [comment]
@BenLubar if this the case:
Would you like to fix this on your side (switching which one is loaded when) or should I do it in here?

**Comment by BenLubar** [comment]
Switching the audio files could have weird consequences, so I'd rather have the captions swapped.

**Pull request merged**
