### PR TITLE
Update nh_officemail_lindasilva_koreana.txt

### PR DESCRIPTION
**Pull request by BRAIN-IS-BACK**
this is Update nh_officemail_lindasilva_koreana.txt
I only now know how to do this. So I thought I just needed to fix it until now, but I knew I had to do **PULL REQUEST.**..

But is there any way to modify several files at once? Do I have to revise it one by one every time?

### CODE REVIEW

**Comment by Blueberryy** [comment]
You can create a Fork and do changes for multiple files if you want and then do Pull Request.

**Comment by BRAIN-IS-BACK** [comment]
@Blueberryy ok, I see. now i can know how can i FORK. thx. :)

**Comment by Blueberryy** [comment]
> @Blueberryy ok, I see. now I can know how to **FORK**. thx. :)

If you have fork already then you can get Github Desktop and just get files from your Fork on your pc, then just open folder and edit files https://desktop.github.com/

**Comment by DukeDukeEm** [comment]
Also, there‘s a wiki if you didn‘t already know. There‘s general stuff about Git(Fork/Pull/Merge) in there too.
https://github.com/ReactiveDrop/reactivedrop_translations/wiki/How-to-translate-using-vscode

**Pull request merged**
