### PR TITLE
Update reactivedrop_swedish.txt

### PR DESCRIPTION
**Pull request by Crazymanbos**
Updated some stuff

### CODE REVIEW

**Comment by Crazymanbos** [comment]
and now we are back

**Comment by DucDuyGaming** [comment]
I checked the error a bit closer. You translated the [english] part of the string instead of the intended part. Can you fix that?

**Comment by Crazymanbos** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhh, thanks for noticing. How do I restore it? If I restore can I just update it or do I have to re-write all of it?

**Comment by jhh8** [comment]
line 1072 and 1288

**Comment by DucDuyGaming** [comment]
You commited in patch-9, so commit it there. One string you put the translated part in [english] instead of the intended part, the second one you modified both

**Comment by Crazymanbos** [comment]
but how do I find patch-9 and how do I edit it?

**Comment by DucDuyGaming** [comment]
[In the folk on your profile](https://github.com/Crazymanbos/reactivedrop_translations/blob/patch-9/resource/reactivedrop_swedish.txt). Updating the branch that is currently being proposed to being merged will automatically update it respective PL

**Comment by Crazymanbos** [comment]
but what does line 1072 originally say? Cuz I changed both there

**Comment by Crazymanbos** [comment]
found it

**Comment by Crazymanbos** [comment]
There we go!! Thank you guys!

**Pull request merged**
