### PR TITLE
update: Add some new Chinese translations of documents

### PR DESCRIPTION
**Pull request by zhongqingsong**
1. Finish baseui's new text
2. Finish achievements's text
3. Complete part of the main file translation, the rest of the follow-up slowly improve

### CODE REVIEW

**Comment by zhongqingsong** [comment]
Uh uh, it's the same problem again. I reported an error in merge check after I made it into Chinese. Build error message: I can not adjust the text, can only add text?
PLZ check and merge, thanks

**Comment by zhongqingsong** [comment]
Then I explain that there are some problems with the old achievement translation.So I do it again.
1, Some old translation has been changed too much, and the meaning of the Original English is quite different. Here, refer to the English original, retranslated and combed again.
2. In terms of the local translation dictionary established according to other translation contents, it unified all the commonly used words in the whole translation contents. Consistency has been maintained, so achievements have varied considerably.
3, part of the translation content, no special treatment. As a result, numbers and text together look tired. Resize the spacing of some text.
4, in the old translation, some misplaced translation, omission translation, re-translation adjustment.

**Comment by zhongqingsong** [comment]
Also, if possible, could you please not merge the resource/ reactiveDrop_sChinese.txt file. There's a lot of content in this file, so if this file gets passed as well. My contribution will always be in the single digits. (I don't know why I didn't submit this file, so it just came up.)
I hope to pass this file through my OWN PR, so as to enhance my PR contribution. (Otherwise, in the long run, someone might think MY contribution is too low, and something bad might happen.)

**Comment by BenLubar** [comment]
GitHub doesn't know that the email address used in the commits that don't have a picture next to them is yours. You just need to add `853421170@qq.com` as one of your email addresses in [the GitHub email settings](https://github.com/settings/emails).

**Comment by BenLubar** [comment]
As for the check failure, there are two things happening:

- `achievements/563560_loc_schinese.vdf` needs to match the achievement names and descriptions in `resource/reactivedrop_schinese.txt` exactly
- There were some duplicate translation keys in basemodui causing weirdness. I've removed them from all languages, so that part is fixed now.

**Comment by zhongqingsong** [comment]
> As for the check failure, there are two things happening:
> 
> * `achievements/563560_loc_schinese.vdf` needs to match the achievement names and descriptions in `resource/reactivedrop_schinese.txt` exactly
> * There were some duplicate translation keys in basemodui causing weirdness. I've removed them from all languages, so that part is fixed now.

Ok ,thanks ,I have added a new Email. (Because this email cannot be pushed to Git normally, I have changed it.)
Achievement translation, I have translated this for some time, in order to unify the whole style, has not submitted. I'm gonna recalibrate that one. Thanks.

**Comment by zhongqingsong** [comment]
> 更加机翻了 很难绷得住

哪里的机翻？你是指还原了英文本意？那翻译的信达雅，首要的就是保证可信度。保证了可信度，才去考虑达、雅。
集体换英语什么东东？没懂这个是什么？

**Comment by zhongqingsong** [comment]
I have been busy recently, so I haven't dealt with this proofreader for the time being.

**Comment by zhongqingsong** [comment]
> > > 更加机翻了 很难绷得住
> > 
> > 
> > 哪里的机翻？你是指还原了英文本意？那翻译的信达雅，首要的就是保证可信度。保证了可信度，才去考虑达、雅。 集体换英语什么东东？没懂这个是什么？
> 
> 如果是房主改成队长还改了原始V社的翻译能达到你的准确度，那我确实没话说了。 包括UI、武器名、一些老成就都是从AS带过来的。老玩家都是用习惯的了你突然改了没有怨言？

Leader本来就英文没有房主这个意思，纯粹是你们自行根据游戏自行修改的；其次UI、武器、成就，本来就是你们一开始就翻译错误的了。
那这种把乱反正如果有问题的，可以找 BenLubar 定夺下，这个有问题的话，回滚回去就完事了，问题不大的。

**Comment by zhongqingsong** [comment]
@BenLubar hello, now we have some differences, if it's convenient for you, we need your help to decide : Which translation mode should be used.

In Dumbstep's opinion, the translation needs to retain the translation of the old version (including the translation of some inaccurate words, and the translation of some words that are not related to the original meaning of English). The advantage is that it is friendly to old players. Players from Alien Swarm are more accustomed to these translations. The not good thing is that there are semantic problems in part of the translation, which is very different from the original text.

As far as i'm concerned, i prefer the new translation direction (keep the old translation on the premise that it is consistent with the English meaning; at the same time, try to use unified vocabulary to accurately translate the English text as much as possible). In doing so, old players need to get used to new accurate translation, which will cause learning costs for old players.

Thanks anyway.

**Comment by zhongqingsong** [comment]
> > > > > 更加机翻了 很难绷得住
> > > > 
> > > > 
> > > > 哪里的机翻？你是指还原了英文本意？那翻译的信达雅，首要的就是保证可信度。保证了可信度，才去考虑达、雅。 集体换英语什么东东？没懂这个是什么？
> > > 
> > > 
> > > 如果是房主改成队长还改了原始V社的翻译能达到你的准确度，那我确实没话说了。 包括UI、武器名、一些老成就都是从AS带过来的。老玩家都是用习惯的了你突然改了没有怨言？
> > 
> > 
> > Leader本来就英文没有房主这个意思，纯粹是你们自行根据游戏自行修改的；其次UI、武器、成就，本来就是你们一开始就翻译错误的了。 那这种把乱反正如果有问题的，可以找 BenLubar 定夺下，这个有问题的话，回滚回去就完事了，问题不大的。
> 
> 什么叫我们自行修改的，你不知道AS的翻译是V社请专业翻译做的本地化处理吗？我就觉得你现在改的有点生硬啊。流行、惯用词玩家才能一眼知道是什么意思。

OK 那我close了，我不参与了。

**Pull request closed without merging**
