### PR TITLE
(multiple) closed captions refinement 1/2

### PR DESCRIPTION
**Pull request by Duke-M-commits**
This is part 1 of 2.
Part 1: gave bloodhounds commander a name
Part 2: will be about standardized formatting in all campaigns

I translated this change into all languages which already had translated captions.

For these languages I made a retranslation which should be checked:
- italian:  @MakinDay please have a look
- japanese: @Deerlord0 please have a look
- koreana: @BRAIN-IS-BACK please have a look
- russian: @Blueberryy please have a look
- schinese: @zhongqingsong please have a look (maybe you could take a look at the tchinese changes too? I don't know)

For these I do not know anyone who could approve them, but since the change is pretty small, it's probably fine. I double checked with different translation engines.
- czech
- danish
- french
- hungarian
- portuguese
- tchinese
- thai
- turkish
- ukrainian

These did not have caption translations, so it's just the new english lines:
- dutch
- finnish
- latam
- norwegian
- polish
- romanian
- spanish
- swedish
- vietnamese

### CODE REVIEW

**Review by Blueberryy — APPROVED** [review]
Looks good.

**Comment by BRAIN-IS-BACK** [comment]
Hmm, Lt. Williams... he seems much cooler just existing as a nameless "bloodhounds commander".

**Comment by Deerlord0** [comment]
Looks good for Japanese.

**Comment by Duke-M-commits** [comment]
Or @ywgATustcbbs maybe you could have a look at the chinese version(s)?

**Comment by Duke-M-commits** [comment]
Or @ModdedMarionette? I'm really not sure whom to ask when it's about the chinese versions.

**Review by zhongqingsong — COMMENTED** [review]
Good, now Commander is finally no longer a John Doe. ^_^
I took a look at schinese and schinese, Nothing's wrong.

**Pull request merged**
