### PR TITLE
(swedish) Update on different files and creation of new files

### PR DESCRIPTION
**Pull request by Crazymanbos**

### CODE REVIEW

**Comment by Duke-M-commits** [comment]
You should replace the urls in your eula into the swedish version too.
Look at what I did with mine: https://github.com/ReactiveDrop/reactivedrop_translations/commit/6e3faabbf6c6dcf8282cec3f628f1c3e667898e8
(don't forget to really test if the links are working)

**Comment by Duke-M-commits** [comment]
Ah, whatever, just use these:
`[url=https://store.steampowered.com/online_conduct/?l=swedish]Steams riktlinjer för uppförande online[/url]`
`[url=https://help.steampowered.com/sv/faqs/view/6862-8119-C23E-EA7B]Regler och riktlinjer för Steam[/url]`

**Comment by Crazymanbos** [comment]
> Ah, whatever, just use these: `[url=https://store.steampowered.com/online_conduct/?l=swedish]Steams riktlinjer för uppförande online[/url]` `[url=https://help.steampowered.com/sv/faqs/view/6862-8119-C23E-EA7B]Regler och riktlinjer för Steam[/url]`

Ah, well most of times the link go into the swedish version by itself, because if your Steam is on Swedish, it will be on Swedish. But I will fix it soon anyway. Working on a translation right now.

**Comment by Duke-M-commits** [comment]
If you're now working on it, convert the pr into a draft (you'll do that on this page, somewhere in the top right). When you're finished convert it back. Why? So Ben doesn't get flooded with messages about your changes.

**Comment by Crazymanbos** [comment]
I dont understand whats failing in the lines now.

**Comment by Duke-M-commits** [comment]
> I dont understand whats failing in the lines now.

remove the indentation on the comments too

**Comment by Crazymanbos** [comment]
Ah, thanks.

**Comment by BenLubar** [comment]
Looks good to merge; will merge once I'm at my PC because I need to manually upload the EULA

**Comment by Crazymanbos** [comment]
> Looks good to merge; will merge once I'm at my PC because I need to manually upload the EULA

Alright. I have translated the name of the Heroes of Interstellar Armed Forces to HaIVS (Hjältar av Interstellär Väpnade Styrkor). I will at some point need to go through everywhere its not yet translated because at those points I didnt know what or how to name it into Swedish.

**Comment by Duke-M-commits** [comment]
> Alright. I have translated the name of the Heroes of Interstellar Armed Forces to HaIVS (Hjältar av Interstellär Väpnade Styrkor)

I'd recommend to translate the long string and leave HoIAF exactly like it is. Abbreviations like this often find their way into textures, guides, wikis, images and multi language conversations on discord or other forums. Thus it's good to leave them as they are to guarantee instant association. You may now think: Hey but then that's totally not the right abbreviation for my noice words. Trust me, that's not as im important as you think.

**Pull request merged**
