### PR TITLE
(Polish) Mainly beta-related stuff, added missing credits, rich presence, surface-level stuff.

### PR DESCRIPTION
**Pull request by Sokolov49**
below-surface level stuff will come soon, halfway through closed captions.. hopefully i haven't screwed up anything anywhere.

### CODE REVIEW

**Comment by Sokolov49** [comment]
honestly i'm kind of lost here, is it supposed to be utf-8 or utf-8-bom? or is it something completely different?
also sorry for the commit spam, it's kind of difficult being unable to use github desktop atm

**Comment by Duke-M-commits** [comment]
It's utf-8 with BOM.
If you change your open pull-request to a draft nobody gets spammed until you think you're finished (then you can change it back).

**Comment by BenLubar** [comment]
> If you change your open pull-request to a draft nobody gets spammed until you think you're finished (then you can change it back).

I still get emails for drafts, but I signed up for email notifications because I want to know what's going on so it's fine

**Comment by BenLubar** [comment]
There's a line with `%+attack%` in it that's missing a quotation mark but I can't find it.

**Comment by Duke-M-commits** [comment]
Line: 345 ends with an tab-stop, maybe it's that?
image

**Comment by Sokolov49** [comment]
There was a duplicate comma at line 510 in valve_polish.txt and I also fixed the tab stop that Duke has pointed out

**Pull request merged**
