### PR TITLE
Update 563560_loc_swedish.vdf

### PR DESCRIPTION
**Pull request by Crazymanbos**
Translated the Reduction campaign.

### CODE REVIEW

**Comment by BenLubar** [comment]
The translation sync tool wants the achievement names and descriptions in reactivedrop_swedish.txt to match these.

**Comment by Crazymanbos** [comment]
Well I dont understand what that means. I guess all my time translating that went to waste then.

**Comment by BenLubar** [comment]
Nope, just need to copy the changed achievement names to https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/resource/reactivedrop_swedish.txt#L3413 and remove the indentation.

**Comment by Crazymanbos** [comment]
So if another page is changed? Does this page need to be changed too for it to work?

**Comment by BenLubar** [comment]
The achievement names and descriptions in reactivedrop_swedish.txt and 563560_loc_swedish.vdf need to match is all.

**Pull request closed without merging**
