### PR TITLE
traditional chinese translation

### PR DESCRIPTION
**Pull request by mewindng**

### CODE REVIEW

**Comment by mewindng** [comment]
added traditional chinese translation

**Comment by mewindng** [comment]
(traditional chinese) vgui and server

**Comment by BenLubar** [comment]
Thanks! Can I have a link to your Steam profile so I can give you the Translator medal?

**Comment by mewindng** [comment]
> Thanks! Can I have a link to your Steam profile so I can give you the Translator medal?

Thank you very much for accepting! ☺️
It's ok I think I dont need the medal for now but still glad that I managed to help ~

**Pull request merged**
