### PR TITLE
새 한국어 번역(New Korean Translation)

### PR DESCRIPTION
**Pull request by BRAIN-IS-BACK**
All right, guys. I'm **back** after a long time, and I'm posting a new translation request.

But when I translated these, I had two questions.

**1. 563560_loc_koreana.vdf**

Including this file, I found the word **Rapture.**
What does this **Rapture** mean? My translator translates Rapture into **great joy, ecstasy, and joy**. I want to know the exact meaning of Rapture.

**2. statsweb_koreana.vdf**

117 lines.

How does "%[1]s on %[2]s" output in the game?
I couldn't translate this part.

Anyway, that's all my questions.
Additionally, I have unified some nouns in **closure_koreana.txt.**

### CODE REVIEW

**Comment by BRAIN-IS-BACK** [comment]
@BenLubar I don't know where the problem is.
I really need your help..... NOW..

**Comment by BenLubar** [comment]
For StatsWeb_AchievementBestTimeOnDifficulty, `%[1]s on %[2]s` translates to something like `1:23 on Brutal`. `%[1]s` is the time and `%[2]s` is the difficulty.

**Comment by BenLubar** [comment]
I think Rapture might be this: https://ko.wikipedia.org/wiki/%ED%9C%B4%EA%B1%B0

**Comment by BRAIN-IS-BACK** [comment]
> @BRAIN-IS-BACK the quotation marks on basemodui_koreana.txt line 1230 are in the wrong place.

ok. i just found this..

**Comment by BRAIN-IS-BACK** [comment]
> Looking into it, will fix anything that doesn't require understanding the language to fix.

????

Has this content been safely merged into Master branches? that is good news.

**Comment by BenLubar** [comment]
Working on the fixes locally because it's easier for me that way and some files need to be manually added to Steam anyway. Looks like it'll all be merged safely once I'm done.

**Pull request merged**
