### PR TITLE
Hullen, Hellen Issues PR

### PR DESCRIPTION
**Pull request by BRAIN-IS-BACK**
One of the reasons for Hullen's translation into Hellen seems to be because of annotations written by translators in the past.

**"The original is Hullen, but it seems to refer to Hellen."**

With this annotation, it seems that Hullen was translated as Hellen.
But now that this turns out to be wrong, I'll translate Hullen properly.

### CODE REVIEW

**Comment by BRAIN-IS-BACK** [comment]
Besides this, I looked for all Helen(헬렌), but the original text was Helen, so I didn't change it.

**Comment by DukeDukeEm** [comment]
resolves #425

**Comment by DukeDukeEm** [comment]
@BRAIN-IS-BACK you may want to remove the comment in both files too
AND you forgot `asw_pda_owner_name_hullen` in reactivedrop_korean.txt

**Comment by BRAIN-IS-BACK** [comment]
> @BRAIN-IS-BACK you may want to remove the comment in both files too

No, I just want a more complete translation with or without annotations.

**Comment by BRAIN-IS-BACK** [comment]
> > @BRAIN-IS-BACK you may want to remove the comment in both files too
> @DukeDukeEm 
> No, I just want a more complete translation with or without annotations.

**Pull request merged**
