### PR TITLE
(swedish) more stuff

### PR DESCRIPTION
**Pull request by Crazymanbos**

### CODE REVIEW

**Comment by Crazymanbos** [comment]
I know what the problem is, the names need to match the other names. I will correct it.

**Comment by Crazymanbos** [comment]
Or not, that requires too much work from me. Because I have to look for all the names.

**Comment by BenLubar** [comment]
https://github.com/ReactiveDrop/reactivedrop_translations/pull/1207/checks has the suggested changes

**Comment by Crazymanbos** [comment]
what is the translation progress document??

**Comment by BenLubar** [comment]
That's https://github.com/ReactiveDrop/reactivedrop_translations/blob/master/PROGRESS.md - it's automatically updated when a pull request is merged. The part you should look at is right above that step, Check for unintended changes. Might take a few seconds to load.

**Pull request closed without merging**
