### PR TITLE
(multiple) better readability for an advanced option

### PR DESCRIPTION
**Pull request by Duke-M-commits**
relates to https://github.com/ReactiveDrop/reactivedrop_translations/issues/939

### CODE REVIEW

**Comment by BenLubar** [comment]
I'm in the process of designing a new settings UI:

https://developer.reactivedrop.com/2024/interface-mockup-settings-video.html

**Comment by Duke-M-commits** [comment]
> I'm in the process of designing a new settings UI:
> 
> https://developer.reactivedrop.com/2024/interface-mockup-settings-video.html

That's great news, tell me if I can be of any help with that :)

**Comment by BenLubar** [comment]
> > I'm in the process of designing a new settings UI:
> > https://developer.reactivedrop.com/2024/interface-mockup-settings-video.html
> 
> That's great news, please tell me if I can be of any help with that :)

If you want to try your hand at making a layout, I've got one left in the settings screens: https://github.com/ReactiveDrop/developer.reactivedrop.com/blob/gh-pages/2024/interface-mockup-settings-options.html

Or if you have any ideas for the audio page: https://developer.reactivedrop.com/2024/interface-mockup-settings-audio.html I'm not quite as happy about how this one ended up as I am with the other three that are ready for implementation.

**Comment by BenLubar** [comment]
Gonna hold onto this PR until we have the options screen layout done just in case we either don't use this string or it gets changed.

**Comment by Duke-M-commits** [comment]
It looks like I effed up the conflict resolving. Since I can't seem to reverse it, I'll close this one and reimplement it later.

**Pull request closed without merging**
