### PR TITLE
translate updated lines, remove date from end of acc32 mails.

### PR DESCRIPTION
**Pull request by Deerlord0**
Date in tilarus01port_SideStory2 and nh_officemail_lindasilva mails looks something wrong.
They took 15 months or 4 years to a reply.

### CODE REVIEW

**Comment by BenLubar** [comment]
paging @jhh8 for the date thing

**Comment by BenLubar** [comment]
paging @jhh8 for the date thing

**Comment by BenLubar** [comment]
paging @Stralke for the Nam Humanum one

@geotavros what do you want to do with the Tilarus-5 mail?

**Comment by DukeDukeEm** [comment]
I'll correct the tilarus stuff, not only are the dates wrong, also Ross seems to write to himself in the second inbox mail.

**Comment by Stralke** [comment]
Thanks a lot for the report, we've pushed a lil update to fix it :)

**Comment by Deerlord0** [comment]
confirmed. Thanks for the fix!

**Pull request merged**
